language: scala

scala:
  - 2.10.7
  - 2.11.12
jdk:
  - openjdk8
matrix:
  include:
  - scala: 2.12.8
    jdk: openjdk8
    script:
      - sbt clean scalafmtCheckAll coverage test coverageReport
      - sbt ++$TRAVIS_SCALA_VERSION! "test"
      - sbt ++$TRAVIS_SCALA_VERSION! "benchmarkJVM/test:compile"
      - sbt ++$TRAVIS_SCALA_VERSION! "benchmarkJS/test:compile"
      #  - sbt ++$TRAVIS_SCALA_VERSION "+scalaJsonJVM/mimaReportBinaryIssues"

  - scala: 2.13.0
    jdk: openjdk8
    env: RUN_MIMA=false
    script:
      - sbt ++$TRAVIS_SCALA_VERSION! "test"

script:
  - sbt clean coverage test coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION! "test"
  - sbt ++$TRAVIS_SCALA_VERSION! "benchmarkJVM/test:compile"
  - sbt ++$TRAVIS_SCALA_VERSION! "benchmarkJS/test:compile"

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
cache:
  directories:
    - $HOME/.sbt/1.0/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
